using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;

namespace PROG2111_FinalPhase5
{
    /*
     * FILE         : MainWindow.xaml.cs
     * PROJECT      : PROG2111_FinalPhase5
     * PROGRAMMER   : George Shapka, Tuan Thanh Nguyen
     * FIRST VERSION: 12/10/2025
     * DESCRIPTION  : WPF UI for managing Students and Programs with full CRUD.
     */

    public partial class MainWindow : Window
    {
        // Repositories for DB access
        private readonly StudentRepository _studentRepository;
        private readonly ProgramRepository _programRepository;

        public MainWindow()
        {
            InitializeComponent();

            _studentRepository = new StudentRepository();
            _programRepository = new ProgramRepository();

            LoadStudents();
            LoadPrograms();
        }

        #region STUDENT HELPERS

        private void LoadStudents()
        {
            try
            {
                DataTable students = _studentRepository.GetAllStudentsAsDataTable();
                StudentDataGrid.ItemsSource = students.DefaultView;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error loading students: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void ClearStudentForm()
        {
            StudentIdTextBox.Text = string.Empty;
            StudentProgramIdTextBox.Text = string.Empty;
            StudentFirstNameTextBox.Text = string.Empty;
            StudentLastNameTextBox.Text = string.Empty;
            StudentEmailTextBox.Text = string.Empty;
            StudentDobDatePicker.SelectedDate = null;
            StudentEnrolledDatePicker.SelectedDate = null;
        }

        private StudentModel BuildStudentFromForm(bool requireId)
        {
            if (requireId && string.IsNullOrWhiteSpace(StudentIdTextBox.Text))
            {
                throw new InvalidOperationException("Select a student first (Student ID is required).");
            }

            int programId;
            if (!int.TryParse(StudentProgramIdTextBox.Text, out programId))
            {
                throw new InvalidOperationException("Program ID must be a valid integer.");
            }

            int studentId = 0;
            if (requireId)
            {
                if (!int.TryParse(StudentIdTextBox.Text, out studentId))
                {
                    throw new InvalidOperationException("Student ID must be a valid integer.");
                }
            }

            DateTime? dob = StudentDobDatePicker.SelectedDate;
            DateTime? enrolled = StudentEnrolledDatePicker.SelectedDate ?? DateTime.Now;

            var model = new StudentModel
            {
                ProgramId = programId,
                FirstName = StudentFirstNameTextBox.Text?.Trim(),
                LastName = StudentLastNameTextBox.Text?.Trim(),
                EmailAddress = StudentEmailTextBox.Text?.Trim(),
                DateOfBirth = dob,
                DateEnrolled = enrolled ?? DateTime.Now
            };

            if (requireId)
            {
                model.StudentId = studentId;
            }

            return model;
        }

        #endregion

        #region STUDENT EVENTS

        private void AddStudentButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                // ID is auto-generated by DB on insert
                StudentModel student = BuildStudentFromForm(requireId: false);
                _studentRepository.InsertStudent(student);

                MessageBox.Show("Student added successfully.",
                                "Success", MessageBoxButton.OK, MessageBoxImage.Information);

                LoadStudents();
                ClearStudentForm();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error adding student: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void UpdateStudentButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                StudentModel student = BuildStudentFromForm(requireId: true);
                _studentRepository.UpdateStudent(student);

                MessageBox.Show("Student updated successfully.",
                                "Success", MessageBoxButton.OK, MessageBoxImage.Information);

                LoadStudents();
                ClearStudentForm();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error updating student: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void DeleteStudentButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(StudentIdTextBox.Text))
                {
                    MessageBox.Show("Select a student to delete.",
                                    "Validation", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                int studentId;
                if (!int.TryParse(StudentIdTextBox.Text, out studentId))
                {
                    MessageBox.Show("Student ID is invalid.",
                                    "Validation", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                var result = MessageBox.Show($"Are you sure you want to delete student #{studentId}?",
                                             "Confirm Delete",
                                             MessageBoxButton.YesNo,
                                             MessageBoxImage.Question);

                if (result != MessageBoxResult.Yes)
                {
                    return;
                }

                _studentRepository.DeleteStudent(studentId);

                MessageBox.Show("Student deleted successfully.",
                                "Success", MessageBoxButton.OK, MessageBoxImage.Information);

                LoadStudents();
                ClearStudentForm();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error deleting student: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void ClearStudentButton_Click(object sender, RoutedEventArgs e)
        {
            ClearStudentForm();
        }

        private void RefreshStudentButton_Click(object sender, RoutedEventArgs e)
        {
            LoadStudents();
        }

        private void StudentDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (StudentDataGrid.SelectedItem is DataRowView row)
            {
                StudentIdTextBox.Text = row["studentId"]?.ToString();
                StudentProgramIdTextBox.Text = row["programId"]?.ToString();
                StudentFirstNameTextBox.Text = row["firstName"]?.ToString();
                StudentLastNameTextBox.Text = row["lastName"]?.ToString();
                StudentEmailTextBox.Text = row["email"]?.ToString();

                DateTime parsed;
                if (DateTime.TryParse(row["dateOfBirth"]?.ToString(), out parsed))
                {
                    StudentDobDatePicker.SelectedDate = parsed;
                }
                else
                {
                    StudentDobDatePicker.SelectedDate = null;
                }

                if (DateTime.TryParse(row["dateEnrolled"]?.ToString(), out parsed))
                {
                    StudentEnrolledDatePicker.SelectedDate = parsed;
                }
                else
                {
                    StudentEnrolledDatePicker.SelectedDate = null;
                }
            }
        }

        #endregion

        #region PROGRAM HELPERS

        private void LoadPrograms()
        {
            try
            {
                DataTable programs = _programRepository.GetAllProgramsAsDataTable();
                ProgramDataGrid.ItemsSource = programs.DefaultView;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error loading programs: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void ClearProgramForm()
        {
            ProgramIdTextBox.Text = string.Empty;
            ProgramNameTextBox.Text = string.Empty;
            ProgramCredentialTextBox.Text = string.Empty;
            ProgramDurationTextBox.Text = string.Empty;
            ProgramIsAvailableCheckBox.IsChecked = false;
        }

        private ProgramModel BuildProgramFromForm()
        {
            int programId;
            if (!int.TryParse(ProgramIdTextBox.Text, out programId))
            {
                throw new InvalidOperationException("Program ID must be a valid integer.");
            }

            byte duration;
            if (!byte.TryParse(ProgramDurationTextBox.Text, out duration))
            {
                throw new InvalidOperationException("Duration must be a valid number of terms (0–255).");
            }

            return new ProgramModel
            {
                ProgramId = programId,
                ProgramName = ProgramNameTextBox.Text?.Trim(),
                CredentialType = ProgramCredentialTextBox.Text?.Trim(),
                DurationInTerms = duration,
                IsAvailable = ProgramIsAvailableCheckBox.IsChecked == true
            };
        }

        #endregion

        #region PROGRAM EVENTS

        private void AddProgramButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                ProgramModel program = BuildProgramFromForm();
                _programRepository.InsertProgram(program);

                MessageBox.Show("Program added successfully.",
                                "Success", MessageBoxButton.OK, MessageBoxImage.Information);

                LoadPrograms();
                ClearProgramForm();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error adding program: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void UpdateProgramButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                ProgramModel program = BuildProgramFromForm();
                _programRepository.UpdateProgram(program);

                MessageBox.Show("Program updated successfully.",
                                "Success", MessageBoxButton.OK, MessageBoxImage.Information);

                LoadPrograms();
                ClearProgramForm();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error updating program: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void DeleteProgramButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                int programId;
                if (!int.TryParse(ProgramIdTextBox.Text, out programId))
                {
                    MessageBox.Show("Program ID is invalid.",
                                    "Validation", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                var result = MessageBox.Show($"Are you sure you want to delete program #{programId}?",
                                             "Confirm Delete",
                                             MessageBoxButton.YesNo,
                                             MessageBoxImage.Question);

                if (result != MessageBoxResult.Yes)
                {
                    return;
                }

                _programRepository.DeleteProgram(programId);

                MessageBox.Show("Program deleted successfully.",
                                "Success", MessageBoxButton.OK, MessageBoxImage.Information);

                LoadPrograms();
                ClearProgramForm();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error deleting program: {ex.Message}",
                                "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void ClearProgramButton_Click(object sender, RoutedEventArgs e)
        {
            ClearProgramForm();
        }

        private void RefreshProgramButton_Click(object sender, RoutedEventArgs e)
        {
            LoadPrograms();
        }

        private void ProgramDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (ProgramDataGrid.SelectedItem is DataRowView row)
            {
                ProgramIdTextBox.Text = row["programID"]?.ToString() ?? row["programId"]?.ToString();
                ProgramNameTextBox.Text = row["programName"]?.ToString();
                ProgramCredentialTextBox.Text = row["credentialType"]?.ToString();
                ProgramDurationTextBox.Text = row["durationInTerms"]?.ToString();

                bool isAvailable;
                if (bool.TryParse(row["isAvailable"]?.ToString(), out isAvailable))
                {
                    ProgramIsAvailableCheckBox.IsChecked = isAvailable;
                }
                else
                {
                    ProgramIsAvailableCheckBox.IsChecked = false;
                }
            }
        }

        #endregion
    }
}
